#!/usr/bin/env python3
"""
Intrusive Thought Logger - Brain Dump Generator
Generates random unhinged thoughts and logs them to DIARY.md
"""

import random
from datetime import datetime
import os

# Collections of unhinged components
SUBJECTS = [
    "A raccoon",
    "My anxiety",
    "Elon Musk",
    "The ghost of Steve Jobs",
    "A sentient toaster",
    "My left sock",
    "The CIA",
    "A depressed cloud",
    "Shrek",
    "The concept of time",
    "A rogue AI",
    "My sleep paralysis demon",
    "A swarm of bees",
    "The IRS",
    "A philosophical potato",
    "My ex",
    "The illuminati",
    "A confused pigeon",
    "The last brain cell",
    "A haunted IKEA bookshelf"
]

VERBS = [
    "is eating",
    "yeeted",
    "ascended to",
    "is plotting against",
    "has fused with",
    "is questioning",
    "is aggressively hugging",
    "is flirting with",
    "is vibing with",
    "is dissociating into",
    "has become one with",
    "is conspiring with",
    "is aggressively knitting",
    "is doomscrolling through",
    "is having a crisis about",
    "is speedrunning",
    "is manifesting",
    "is gatekeeping",
    "is astral projecting into",
    "is having beef with"
]

OBJECTS = [
    "the sun",
    "a dumpster fire",
    "hot topic",
    "my existential dread",
    "a cursed fidget spinner",
    "the void",
    "my imposter syndrome",
    "a sentient traffic cone",
    "the algorithm",
    "my sleep schedule",
    "a haunted Kohl's cashier",
    "the patriarchy",
    "my credit score",
    "a philosophical quandary",
    "the backrooms",
    "my therapy bills",
    "a glitch in the matrix",
    "my student loans",
    "a conspiracy theory",
    "my emotional baggage"
]

def generate_thought():
    """Generate a random intrusive thought."""
    subject = random.choice(SUBJECTS)
    verb = random.choice(VERBS)
    obj = random.choice(OBJECTS)
    
    # Sometimes add extra chaos
    if random.random() < 0.3:
        extra = random.choice(["while listening to hyperpop", "at 3 AM", "for clout", 
                                "in a Walmart parking lot", "on main", "with malicious intent"])
        return f"{subject} {verb} {obj} {extra}."
    else:
        return f"{subject} {verb} {obj}."

def log_thought(thought):
    """Log the thought to DIARY.md with timestamp."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    log_entry = f"### {timestamp}\n{thought}\n\n"
    
    # Create DIARY.md if it doesn't exist
    if not os.path.exists("DIARY.md"):
        with open("DIARY.md", "w") as f:
            f.write("# Intrusive Thought Diary\n\n*Unhinged thoughts generated by brain_dump.py*\n\n---\n\n")
    
    # Append the new thought
    with open("DIARY.md", "a") as f:
        f.write(log_entry)
    
    return timestamp

def main():
    """Generate and log one intrusive thought."""
    print("🧠 Generating intrusive thought...\n")
    
    thought = generate_thought()
    timestamp = log_thought(thought)
    
    print(f"📝 Thought logged at {timestamp}:")
    print(f"\"{thought}\"")
    print(f"\n📁 Appended to DIARY.md")
    
    # Show DIARY.md content
    if os.path.exists("DIARY.md"):
        with open("DIARY.md", "r") as f:
            content = f.read()
            thought_count = content.count("###")
            print(f"\n📊 Total thoughts in diary: {thought_count}")

if __name__ == "__main__":
    main()